config/routes.rb
Ibmsc2::Application.routes.draw do
  resources :tournaments

  resources :maps

  root :to => 'results#index'

  match '/matches/upload' => 'matches#upload'
  match '/matches/submit-duplicate' => 'matches#submit_duplicate'
  resources :matches

  resources :players

  match '/handicaps' => 'who_to_play#index'
  match ':action'    => 'static#:action'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :matches, :order => 'time DESC, id DESC'
  has_many :standings, :order => 'points DESC'
  has_many :players, :through => :standings, :order => 'points DESC'

  validates_presence_of :name, :start_date

  def self.current
    Tournament.order( :start_date ).last
  end

  def self.random_adjustment
    20 + rand( 31 )
  end

  def self.starting_points( league )
    1000
  end

  def self.handicap( player_league, opponent_league )
    if player_league.nil? || opponent_league.nil? || ( player_league - opponent_league ).abs < 2
      return 0
    end

    if player_league > opponent_league
      10 * ( player_league - opponent_league - 1 )
    else
      10 * ( player_league - opponent_league + 1 )
    end
  end

  def compute_results
    matches = self.matches

    wins = {}
    wins.default = 0
    losses = {}
    losses.default = 0

    matches.each do |match|
      wins[match.winner_id] += 1
      losses[match.loser_id] += 1
    end

    players = []
    points = {}
    ranks = {}

    last_points = -1
    rank = 0
    rank_count = 1

    self.standings.each do |standing|
      if wins[standing.player_id] > 0 || losses[standing.player_id] > 0

        players.push standing.player_id
        points[standing.player_id] = standing.points

        if standing.points != last_points
          last_points = standing.points
          rank += rank_count
          rank_count = 0
        end

        rank_count += 1
        ranks[standing.player_id] = rank
      end
    end

    names = {}
    leagues = {}

    Player.all.each do |player|
      names[player.id] = player.name
      leagues[player.id] = player.league_name
    end

    return players, names, leagues, points, ranks, wins, losses, matches
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  # GET /tournaments
  def index
    @tournaments = Tournament.order( 'start_date DESC' )

    @current_tournament = Tournament.current

    @participants = {}
    @tournaments.each do |tournament|
      @participants[tournament.id] = Set.new
    end

    Match.all.each do |match|
      @participants[match.tournament_id].add match.winner_id
      @participants[match.tournament_id].add match.loser_id
    end

    @winners = {}
    @tournaments.each do |tournament|
      if tournament != @current_tournament
        highest_standing = tournament.standings.first

        if !highest_standing.nil?
          @winners[tournament.id] = highest_standing.player
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /tournaments/1
  def show
    @tournament = Tournament.find(params[:id])
    
    @players, @names, @leagues, @points, @ranks, @wins, @losses = @tournament.compute_results

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /tournaments/1/edit
  def edit
    @tournament = Tournament.find(params[:id])
  end

  # POST /tournaments
  def create
    @tournament = Tournament.new(params[:tournament])
    @tournament.start_date = DateTime.now

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to(@tournament, :notice => 'Tournament was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /tournaments/1
  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to(@tournament, :notice => 'Tournament was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /tournaments/1
  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to(tournaments_url) }
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div class="alert alert-error alert-block">
      <h4>The tournament could not be started</h4>
      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="controls">
    <%= f.submit( 'Start tournament', :class => 'btn btn-primary' ) %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1>Tournaments<small class="pull-right"><%= link_to "Start new tournament", new_tournament_path, :class => "btn btn-primary" %></small></h1>

      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Start Date</th>
            <th>Participants</th>
            <th>Games</th>
            <th>Winner</th>
          </tr>
        </thead>
        <% @tournaments.each do |tournament| %>
        <tr>
          <td><%= link_to tournament.name, tournament_path( tournament ) %></td>
          <td><%= tournament.start_date.getlocal.strftime( "%b %d %Y" ) %></td>
          <td><%= @participants[tournament.id].size %></td>
          <td><%= tournament.matches.size %></td>
          <td>
            <% if !@winners.has_key? tournament.id %>
            --
            <% else %>
            <%= image_tag( '/images/' + @winners[tournament.id].league_name + '.png' ) %>
            <%= link_to( @winners[tournament.id].name, player_path( @winners[tournament.id] ) ) %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/tournaments/new.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1>Start new tournament</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tournaments/show.html.erb
<div class="container">
  <div class="row">
    <div class="span5">
      <h1><%= @tournament.name %> <small><%= @tournament == Tournament.current ? 'Standings' : 'Final Results' %></small></h1>

      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Player</th>
            <th>Points</th>
            <th>Record</th>
          </tr>
        </thead>
        <% @players.each do |player_id| %>
        <tr>
          <td><%= @ranks[player_id] %></td>
          <td>
            <%= image_tag( '/images/' + @leagues[player_id] + '.png' ) %>
            <%= link_to @names[player_id], '/players/' + player_id.to_s %>
          </td>
          <td><%= @points[player_id] %></td>
          <td><%= @wins[player_id].to_s + '-' + @losses[player_id].to_s %></td>
        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>