config/routes.rb
Ibmsc2::Application.routes.draw do
  resources :tournaments

  resources :maps

  root :to => 'results#index'

  match '/matches/upload' => 'matches#upload'
  match '/matches/submit-duplicate' => 'matches#submit_duplicate'
  resources :matches

  resources :players

  match '/handicaps' => 'who_to_play#index'
  match ':action'    => 'static#:action'

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @tournament = Tournament.current
    @players = []
    @matches = []

    if !@tournament.nil?
      @players, @names, @leagues, @points, @ranks, @wins, @losses, @matches = @tournament.compute_results
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/index.html.erb
<div class="container">
  <div class="row">

    <% if @tournament.nil? %>
    <div class="span6">
      No tournaments exist yet. <%= link_to 'Start a tournament', new_tournament_path %> and create some players to begin.
    </div>
    <% else %>

    <div class="span5">
      <h1>Standings</h1>
      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Player</th>
            <th>Points</th>
            <th>Record</th>
          </tr>
        </thead>
        <% @players.each do |player_id| %>
        <tr>
          <td><%= @ranks[player_id] %></td>
          <td>
            <%= image_tag( '/images/' + @leagues[player_id] + '.png' ) %>
            <%= link_to @names[player_id], '/players/' + player_id.to_s %>
          </td>
          <td><%= @points[player_id] %></td>
          <td><%= @wins[player_id].to_s + '-' + @losses[player_id].to_s %></td>
        </tr>
        <% end %>
      </table>
    </div>

    <div class="span7">
      <h1>Games<small class="pull-right"><%= link_to 'Record game', new_match_path, :class => 'btn btn-primary' %></small></h1>
      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Winner</th>
            <th>Loser</th>
            <th>Details</th>
          </tr>
        </thead>
        <% @matches.each do |match| %>
        <tr>
          <td><span class=""><%= match.ago( Time.now ) %></span></td>
          <td>
            <%= image_tag( '/images/' + @leagues[match.winner_id] + '.png' ) %>
            <%= link_to @names[match.winner_id], '/players/' + match.winner_id.to_s %>
            (+<%= match.winner_points %>)
          </td>
          <td>
            <%= image_tag( '/images/' + @leagues[match.loser_id] + '.png' ) %>
            <%= link_to @names[match.loser_id], '/players/' + match.loser_id.to_s %>
            (<%= match.loser_points %>)
          </td>
          <td>
            <%= link_to 'details', match_path( match ) %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    
  <% end %>
  </div>
</div>