config/routes.rb
Ibmsc2::Application.routes.draw do
  resources :tournaments

  resources :maps

  root :to => 'results#index'

  match '/matches/upload' => 'matches#upload'
  match '/matches/submit-duplicate' => 'matches#submit_duplicate'
  resources :matches

  resources :players

  match '/handicaps' => 'who_to_play#index'
  match ':action'    => 'static#:action'

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :games_won, :class_name => "Match", :foreign_key => "winner_id", :dependent => :delete_all
  has_many :games_lost, :class_name => "Match", :foreign_key => "loser_id", :dependent => :delete_all
  has_many :standings
  has_many :tournaments, :through => :standings

  validates :name, :presence => true
  validates_format_of :character_code, :with => /^$|^[0-9]{2,3}$/, :message => "must be 3 or 4 digits long"

  def name_with_code
    if character_code.nil?
      name
    else
      name + "." + character_code.to_s
    end
  end

  def points
    standing = standings.where( :tournament_id => Tournament.current.id ).first
    standing.nil? ? Tournament.starting_points( self.league ) : standing.points
  end

  def rank
    1 + Standing.count( :conditions => ['tournament_id = ? and points > ?', Tournament.current.id, points] )
  end

  def record_this_season
    wins = Match.count( :conditions => ['winner_id = ? and tournament_id = ?', id, Tournament.current.id] )
    losses = Match.count( :conditions => ['loser_id = ? and tournament_id = ?', id, Tournament.current.id] )
    wins.to_s + '-' + losses.to_s
  end

  def record_all_time
    wins = Match.count( :conditions => ['winner_id = ?', id] )
    losses = Match.count( :conditions => ['loser_id = ?', id] )
    wins.to_s + '-' + losses.to_s
  end

  def league_name
    return "master"   if league == 1
    return "diamond"  if league == 2
    return "platinum" if league == 3
    return "gold"     if league == 4
    return "silver"   if league == 5
    return "bronze"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.xml
  def index
    @games_played = {}
    @games_played.default = 0

    Match.all.each do |match|
      @games_played[match.winner_id] += 1
      @games_played[match.loser_id] += 1
    end

    @players = Player.all.sort { |a,b| a.name.downcase <=> b.name.downcase }

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find( params[:id] )
    @matches = Match.order( 'time DESC, id DESC ' ).where( 'winner_id = ? or loser_id = ?', @player.id, @player.id )

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path, :notice => 'Player was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url) }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for( @player ) do |f| %>
  <% if @player.errors.any? %>
    <div class="alert alert-error alert-block">
      <h4>The changes could not be saved</h4>
      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <%= f.label :character_code %>
    <div class="controls"><%= f.text_field :character_code %></div>
  </div>
  <div class="control-group">
    <%= f.label :league %>
    <div class="controls">
      <%= f.select :league, [ ['--', nil], ['Master', 1], ['Diamond', 2], ['Platinum', 3], ['Gold', 4], ['Silver', 5], ['Bronze', 6] ] %>
    </div>
  </div>
  <div class="controls">
    <%= f.submit( ( @starting_points.nil? ? 'Save' : 'Create player' ), :class => 'btn btn-primary' ) %>
  </div>
<% end %>

app/views/players/_league_icon.html.erb
<%= image_tag( '/images/' + player.league_name + '.png' ) %>

app/views/players/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1>Editing <%= @player.name %></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<div class="container">
  <div class="row">
    <div class="span5">

      <h1>Players<small class="pull-right"><%= link_to "New player", new_player_path, :class => "btn btn-primary" %></small></h1>

      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Character Code</th>
            <th>Games Played</th>
          </tr>
        </thead>
        <% @players.each do |player| %>
        <tr>
          <td>
            <%= image_tag( '/images/' + player.league_name + '.png' ) %>
            <%= link_to player.name, player_path( player ) %>
          </td>
          <td><%= player.character_code || '--' %></td>
          <td><%= @games_played[player.id] %></td>
        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/players/new.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <h1>New player</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<div class="container">
  <div class="row">

    <div class="span4">

      <h1>
        <%= @player.name %>
        <small class="pull-right"><%= link_to "Edit", edit_player_path( @player ), :class => "btn" %></small>
      </h1>

      <div class="well well-small">
        <dl class="dl-horizontal">
          <dt>Character code</dt><dd><%= @player.character_code || '--' %></dd>
          <dt>League</dt><dd><%= render 'league_icon', :player => @player %></dd>
          <dt>Points</dt><dd><%= @player.points %></dd>
          <dt>Record this season</dt><dd><%= @player.record_this_season %></dd>
          <dt>Record All time</dt><dd><%= @player.record_all_time %></dd>
        </dl>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="span6">

      <h4>Match History</h4>
      
      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Tournament</th>
            <th>Date</th>
            <th>Opponent</th>
            <th>Result</th>
            <th>Details</th>
          </tr>
        </thead>
        <% @matches.each do |match| %>
        <tr>
          <td><%= link_to match.tournament.name, tournament_path( match.tournament ) %></td>
          <td><%= match.ago( Time.now ) %></td>
          <td>
            <%= render 'league_icon', :player => match.opponent( @player ) %>
            <%= link_to match.opponent( @player ).name, player_path( match.opponent( @player ) ) %>
          </td>
          <td>
            <%= match.win?( @player ) ? 'Win' : 'Loss' %>
            (<%= match.points( @player ) >= 0 ? "+" : "" %><%= match.points( @player ) %>)
          </td>
          <td>
            <%= link_to 'details', match_path( match ) %>
          </td>
        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>